apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    # Everytime scaffold will be started, all the config files will get executed and create objects for us. Wherease will delete all the objects when scaffold will be stoped.
    # telling scaffold to montior all the config files and run 'kubectl apply -f <file_name>.yaml' if anything changes inside them.
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-298808
  artifacts:
    - image: ankitverma0810/auth
    # - image: us.gcr.io/ticketing-dev-298808/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ankitverma0810/client
    # - image: us.gcr.io/ticketing-dev-298808/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: ankitverma0810/tickets
    # - image: us.gcr.io/ticketing-dev-298808/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ankitverma0810/orders
    # - image: us.gcr.io/ticketing-dev-298808/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ankitverma0810/expiration
    # - image: us.gcr.io/ticketing-dev-298808/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ankitverma0810/payments
    # - image: us.gcr.io/ticketing-dev-298808/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    