apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: ankitverma0810/tickets
          # image: us.gcr.io/ticketing-dev-298808/tickets
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  # path of the pod name
                  fieldPath: metadata.name
            - name: NATS_URL
              # name of the service defined in the nats-depl file
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              # name of the clusterId define in the nats-depl file
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
              # This name will be set as one of the env variable in the tickets container
            - name: JWT_KEY
              valueFrom:
                # name and key which we have defined while creating the secret
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  type: ClusterIP
  ports: 
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000