name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build docker image
        run: cd client && docker build -t ankitverma0810/client .
      - name: docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: push docker image
        run: docker push ankitverma0810/client
      - name: install doctl into github container and authenticate
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Access ticketing cluster from digital ocean and switch context
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: restart deployment to use latest docker image
        run: kubectl rollout restart deployment client-depl
