name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install doctl into github container and authenticate
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Access ticketing cluster from digital ocean and switch context
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: apply infra k8s files
        run: kubectl apply -f infra/k8s
