name: tests-tickets

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Unit Tests
        run: cd tickets && npm install && npm run test:ci
