name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Unit Tests
        run: cd payments && npm install && npm run test:ci
