name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Unit Tests
        run: cd orders && npm install && npm run test:ci
