name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Unit Tests
        run: cd auth && npm install && npm run test:ci
